# This is a basic workflow to help you get started with Actions

name: Push to heroku

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Create .env.test file
        run: |
          touch .env.test
          echo MYSQL_USER=${{ secrets.MYSQL_USER }} >> .env.test
          echo MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }} >> .env.test
          echo MYSQL_DATABASE=${{ secrets.MYSQL_DATABASE }} >> .env.test
          echo MYSQL_QUERY_LOGS=${{ secrets.MYSQL_QUERY_LOGS }} >> .env.test
          echo HOST=${{ secrets.HOST }} >> .env.test
          echo DOMAIN=${{ secrets.DOMAIN }} >> .env.test
          echo PORT=${{ secrets.PORT }} >> .env.test
          echo NODE_ENV=${{ secrets.NODE_ENV }} >> .env.test
          echo API_KEY=${{ secrets.API_KEY }} >> .env.test
      - name: Build and Test
        uses: actions/setup-node@v2
        with:
          node-version: 12.x
      - run: npm install
      - run: npm test
      - run: npm run build
      - name: Login to Heroku Container registry
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku container:login
      - name: Push to heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku container:push -a radiant-inlet-71679 web
      - name: Creating Release
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku container:release -a radiant-inlet-71679 web
